### ISSUE TITLE
populate state dynamically when country is chosen

### ISSUE THREAD

**Issue by jinnyroxs** [katzwebservices/Gravity-Forms-Salesforce#167]
Hi,

Is there anyway to populate state dynamically when a country a chosen ?

For example

Country: Malaysia
State: a list of states in malaysia will be shown

**Comment by zackkatz** [comment]
Hi - this may be coming to Gravity Forms in the future. I would suggest asking them about it.

**Comment by jinnyroxs** [comment]
i can't find 
record type in
3. Map form fields to Salesforce fields.

**Comment by coadr** [comment]
any updates about the record type? @jinnyroxs
