### ISSUE TITLE
Gravity Forms 1.9

### ISSUE THREAD

**Issue by adamdanielmedia** [katzwebservices/Gravity-Forms-Salesforce#169]
Is the plugin ready for Gravity Forms 1.9?

**Comment by ak47marx** [comment]
Nope, when activated and trying to enter company ID, red message says "This add-on needs to be updated. Please contact the developer."

**Comment by adamdanielmedia** [comment]
Thanks. Hoping the developer sees this thread and updates soon!

**Comment by zackkatz** [comment]
This doesn't affect the functionality. That being said, the error is fixed in the next update.
