### ISSUE TITLE
Salesforce Add On not passing Yes/No Values

### ISSUE THREAD

**Issue by ltweb** [katzwebservices/Gravity-Forms-Salesforce#173]
I have been looking into anything on the issue. I use a radiobox on GravityForms to pass a yes or no value to salesforce, but the function salesforce is looking for is a checkbox on the custom field I have set up. Is it not possible to set up a custom field that can display a yes or no result from an outside form?

thanks!

**Comment by zackkatz** [comment]
Set your Gravity Forms field to use values and define the value as `1` or `0` for the radio.
