### ISSUE TITLE
Not working with 1.9

### ISSUE THREAD

**Issue by ak47marx** [katzwebservices/Gravity-Forms-Salesforce#174]
Love the plugin but it does not work with 1.9 gravityforms. When activated and trying to enter company ID, red message says "This add-on needs to be updated. Please contact the developer."

Zack, can you please take a look and let us know when you can update?
Thanks.

**Comment by graph-io** [comment]
I'm seeing the same issue

**Comment by graph-io** [comment]
@ak47marx Do you by chance have user role editor plugin installed? I got this error and the link under forms to Salesforce did not show up. This was due to none of the GF capabilities being checked for the administrator role. After adding the capabilities to the role no problems here...

**Comment by ak47marx** [comment]
Nope, don't have anything installed, but thanks for the info, will try, maybe i can get it fixed also.

**Comment by zackkatz** [comment]
I'll work on fixing this ASAP.

**Comment by zackkatz** [comment]
The error shouldn't affect functionality. I'm releasing an update that fixes it, but it won't prevent anything from working as normal.
