### ISSUE TITLE
This add-on needs to be updated. Please contact the developer.!

### ISSUE THREAD

**Issue by david-j-m** [katzwebservices/Gravity-Forms-Salesforce#175]
Hi,
 I just installed the Gravity forms Salesforce plugin version 3.1
This message appears at the top of the settings page:

<strong>This add-on needs to be updated. Please contact the developer.</strong>

What should I do?

Thanks for your help
David

**Comment by simplexstudios** [comment]
I am also receiving this error while using the Salesforce API method

**Comment by david-j-m** [comment]
Hi John, I'm not sure how this affects the performance of the plugin, if at
all. My other problem is I'm not seeing anything being passed to
salesforce, and I can't find any tutorials using this plugin, they just
assume you're gravity forms/salesforce guru and everything's obvious, I
know very little about Gravity Forms and even less about Salesforce, so I'm
having a really hard time getting the two connected. If you know any good
tutorials I'd appreciate a link.

Thanks
*(:D*avid

**Comment by simplexstudios** [comment]
David, I would first start with the Gravity Forms: Logging Tool at the bottom of http://www.gravityhelp.com/downloads/ to see what is happening with Salesforce and Gravity Forms.

**Comment by zackkatz** [comment]
This was fixed Feb 17.
