### ISSUE TITLE
is_save_postback deprecated

### ISSUE THREAD

**Issue by travisseitler** [katzwebservices/Gravity-Forms-Salesforce#179]
Thanks for the GF 1.9 compatible update! I may have found a related PHP Notice while looking over my logs for unrelated issues. Here's the stack trace output (cleaned up a bit for readability's sake):

    PHP Notice:
    KWS_GF_Salesforce_Loader::is_save_postback is **deprecated** since version 1.9!
    Use public access level instead.
    in wp-includes/functions.php on line 3378,
    referer: /wp-admin/edit.php
    	
    Stack trace:
    1. {main}() wp-admin/post-new.php:0
    2. include() wp-admin/post-new.php:74
    3. do_action() wp-admin/admin-footer.php:67
    4. call_user_func_array:{wp-includes/plugin.php:496}() wp-includes/plugin.php:496
    5. GFForms::deprecate_add_on_methods() wp-includes/plugin.php:496
    6. _deprecated_function() wp-content/plugins/gravityforms/gravityforms.php:2702
    7. trigger_error() wp-includes/functions.php:3378

It's a notice -- not a warning -- so I'm not too worried about it. Just doing the whole "see something, say something" thing. :+1:

**Comment by zackkatz** [comment]
Fixed in next update. Thanks for reporting.
