### ISSUE TITLE
plugin deprecated error

### ISSUE THREAD

**Issue by pablojara90** [katzwebservices/Gravity-Forms-Salesforce#183]
I'm getting this error at the bottom of each page in the dashboard can you help me?

get_plugin_setting is deprecated since version 1.9! Use public access level instead. in /home4/printdgs/public_html/dev/wp-includes/functions.php on line 3378

Notice: KWSGFAddOn2_2::is_save_postback is deprecated since version 1.9! Use public access level instead. in /home4/printdgs/public_html/dev/wp-includes/functions.php on line 3378

Notice: KWS_GF_Salesforce_Loader::is_save_postback is deprecated since version 1.9! Use public access level instead. in /home4/printdgs/public_html/dev/wp-includes/functions.php on line 3378

**Comment by donaldallen** [comment]
:+1: These are annoying errors.

**Comment by zackkatz** [comment]
Fixed in the next update, even though the warnings *shouldn't* display, but Gravity Forms made it over-aggressive…
