### ISSUE TITLE
Can not authenicate to salesforce what does this mean?

### ISSUE THREAD

**Issue by cease15** [katzwebservices/Gravity-Forms-Salesforce#184]
The Salesforce: API Add-On could not be loaded.

Please contact your hosting provider and ask them to enable support for the following on your server:
PHP Version 5.3 or Higher

As of version 2.7, the Gravity Forms Salesforce API Add-On requires PHP 5.3 or above. Please contact your hosting provider support and ask them to upgrade your server.

If this is not possible, you may download the last version of the plugin that did not require PHP 5.3.

You can use the Salesforce Web-to-Lead Add-on; it doesn’t have the same requirements.

**Comment by zackkatz** [comment]
Contact your host and ask them to upgrade your server to PHP 5.3.
