### ISSUE TITLE
Question on SSL changes

### ISSUE THREAD

**Issue by adamcalyptix** [katzwebservices/Gravity-Forms-Salesforce#188]
I had a question related to the coming changes to Salesforce's HTTPS certificates. Will this affect the integration of Gravity form and Salesforce on our site?

Here's info from Salesforce on the change:

"Salesforce will be replacing current HTTPS certificates, which are signed with a SHA-1 hash algorithm, to new certificates signed with a SHA-256 hash algorithm. Additionally, Salesforce will be consolidating our trusted third party certificate authorities (CA) to leverage only Symantec issued digital certificates."

Thanks again,
-Adam

**Comment by zackkatz** [comment]
I don't think anything will be affected.

**Comment by adamcalyptix** [comment]
Excellent -- thanks Zack!
