### ISSUE TITLE
Salesforce API connection stopped working

### ISSUE THREAD

**Issue by walester** [katzwebservices/Gravity-Forms-Salesforce#193]
I had successfully set up my Gravity forms to Salesforce Lead through the API. Everything seemed to be working fine, but since the beginning of March, it seems to have stopped working. I have not changed anything, but I have upgraded to the latest version of the Gravity Forms plugin. Am I doing something wrong? I can I troubleshoot this problem?

TIA

**Comment by CreoMedia** [comment]
I have had the same experience. Both "Contact Form > New Lead" and "Contact Form > New Opportunity" have stopped working. I've only noticed this after upgrading to the latest Gravity Forms and Wordpress.
Is this a common problem?

**Comment by Asuryan30** [comment]
Same for me.

Actually, When I go to options, I dont see "salesforce API" anymore.   The web to web is still working but .. dates, multipicklist doesnt work (as usual)

**Comment by Asuryan30** [comment]
Ok.

I tried many things and finally I got my solution.    The last vertion of gravity form Salesforce is actually working with the last version of gravity. But, some plugin can cause problems.
In my case, it was "Syntegrate Chart"  I disactivated it and .. everything is working well.

**Comment by swoffaAU** [comment]
After all that stress, it turns out that the version updated had somehow changed my settings from "API" to "Web-to-Lead"... I switched it back to API and it seems to be working now with the latest versions of both plugins.

**Comment by walester** [comment]
swoffaAU identified my problem. For some reason, my settings in the Salesforce plugin for Gravity Forms had changed my settings from "API" to "Web-to-Lead". I reset it to API, and now all seems to be working fine.

Thanks for your help!

**Comment by adamfoale** [comment]
I've got the same problem.  Web-to-Lead stopped working all of a sudden, no errors reported in error.log, switched to API and 'Salesforce API' does not show in the menu at all.  Checking the error logs I noticed:

" WordPress database error Table 'domain_com_au.pt_rg_salesforce' doesn't exist for query."

Uninstalling the plugin and reinstalling does not fix it. Switching back to Web-to-Lead and it's still broken.

Is there anyone from Katz actually looking at these forums?

**Comment by walester** [comment]
Adam,



I was able to fix my problem, based on a posting to the thread.



1.       In WordPress Administration, go to the Gravity Forms/Settings
module

2.       On the tab marked API, verify that “Enable access to the API” is
checked. Click on the Update Settings button near the bottom of the page.

3.       In the tab marked “Salesforce Add-On” verify that in the section
titled “Integration Method, Choose the type of connection to Salesforce”,
that the API section is bulleted. Click on the Update Settings button.

4.       When you test to see if the forms are sending to the Salesforce
API, be sure to completely refresh the page. The cache may be set up to
hold the previous settings.



In my case, upgrading to the latest version of Gravity forms changed my
Integration Method setting from “API” to “Web-to-Lead or Web-to-Case”. I
don’t know why that happened, but once I corrected it, and once I refreshed
the pages on my website that contained the forms, everything started
working again.



I hope this info helps.



Bill





William (Bill) Lester
*Executive Director **- NPOKI*



*From:* Adam [mailto:notifications@github.com]
*Sent:* Tuesday, March 31, 2015 1:09 PM
*To:* katzwebservices/Gravity-Forms-Salesforce
*Cc:* walester
*Subject:* Re: [Gravity-Forms-Salesforce] Salesforce API connection stopped
working (#193)



I've got the same problem. Web-to-Lead stopped working all of a sudden, no
errors reported in error.log, switched to API and 'Salesforce API' does not
show in the menu at all. Checking the error logs I noticed:

" WordPress database error Table 'domain_com_au.pt_rg_salesforce' doesn't
exist for query."

Uninstalling the plugin and reinstalling does not fix it. Switching back to
Web-to-Lead and it's still broken.

Is there anyone from Katz actually looking at these forums?

—
Reply to this email directly or view it on GitHub
<https://github.com/katzwebservices/Gravity-Forms-Salesforce/issues/193#issuecomment-88279130>
.

**Comment by walester** [comment]
Oh, and btw, the Salesforce Plugin for Gravity Forms is a separate plugin
from the main Gravity Forms installation. If for some reason on your setup,
it has become corrupted, you may need to reinstall both plugins.



Hope this info helps.



Bill



William (Bill) Lester
*Executive Director **- NPOKI*



*From:* Adam [mailto:notifications@github.com]
*Sent:* Tuesday, March 31, 2015 1:09 PM
*To:* katzwebservices/Gravity-Forms-Salesforce
*Cc:* walester
*Subject:* Re: [Gravity-Forms-Salesforce] Salesforce API connection stopped
working (#193)



I've got the same problem. Web-to-Lead stopped working all of a sudden, no
errors reported in error.log, switched to API and 'Salesforce API' does not
show in the menu at all. Checking the error logs I noticed:

" WordPress database error Table 'domain_com_au.pt_rg_salesforce' doesn't
exist for query."

Uninstalling the plugin and reinstalling does not fix it. Switching back to
Web-to-Lead and it's still broken.

Is there anyone from Katz actually looking at these forums?

—
Reply to this email directly or view it on GitHub
<https://github.com/katzwebservices/Gravity-Forms-Salesforce/issues/193#issuecomment-88279130>
.

**Comment by adamfoale** [comment]
Thanks walester.  Unfortunately this doesn't work for me.  Enabling the main GF API doesn't impact the Salesforce side of things.  If I set the 'Integration method' to API under 'Salesforce Add-On', I do not get the 'Saleforce API' option in the left hand menu.  

The Web-to-Lead option seems to work ok, but absolutely no leads get through to Saleforce anymore.  This suddenly started happening about a month ago.  Now apparently Salesforce had a major release about the same time so my gut feel is that this plugin has been broken by whatever Saleforce did.

I'd rather not have to do a manual Web-to-Lead submission through the Gravity forms post options, but i may not have a choice at present.

Uninstalling and reinstalling the plugin didn't fix anything, and deactivating and uninstalling the plugin doesn't remove the DB entries (all my feeds were still intact) so i feel that it's not actually doing what it should during this process.  You can never get back to a 'clean slate'.

I also added the Gravity Forms logging plugin and looking at the logs, everything suggests that the records are being added to Salesforce (via web-to-lead):

2015-04-01 9:47:05 - DEBUG --> Entry 946 was added to Salesforce. Here's the available data:

below which is the array of data from the form which all looks correct.

However, there is no record in Saleforce.  Org ID is correct, everything is as it was when it was working 5 weeks ago.

I'm at a loss....

**Comment by walester** [comment]
Adam,



RE: “…If I set the 'Integration method' to API under 'Salesforce Add-On', I
do not get the 'Salesforce API' option in the left hand menu…”



That’s because the Salesforce API option a separate plugin that you have to
download. It’s not part of the Gravity Forms plugin.



Does that help at all?



Bill



William (Bill) Lester
*Executive Director **- NPOKI*



*From:* Adam [mailto:notifications@github.com]
*Sent:* Tuesday, March 31, 2015 4:01 PM
*To:* katzwebservices/Gravity-Forms-Salesforce
*Cc:* walester
*Subject:* Re: [Gravity-Forms-Salesforce] Salesforce API connection stopped
working (#193)



Thanks walester. Unfortunately this doesn't work for me. Enabling the main
GF API doesn't impact the Salesforce side of things. If I set the
'Integration method' to API under 'Salesforce Add-On', I do not get the
'Saleforce API' option in the left hand menu.

The Web-to-Lead option seems to work ok, but absolutely no leads get
through to Saleforce anymore. This suddenly started happening about a month
ago. Now apparently Salesforce had a major release about the same time so
my gut feel is that this plugin has been broken by whatever Saleforce did.

I'd rather not have to do a manual Web-to-Lead submission through the
Gravity forms post options, but i may not have a choice at present.

Uninstalling and reinstalling the plugin didn't fix anything, and
deactivating and uninstalling the plugin doesn't remove the DB entries (all
my feeds were still intact) so i feel that it's not actually doing what it
should during this process. You can never get back to a 'clean slate'.

I also added the Gravity Forms logging plugin and looking at the logs,
everything suggests that the records are being added to Salesforce (via
web-to-lead):

2015-04-01 9:47:05 - DEBUG --> Entry 946 was added to Salesforce. Here's
the available data:

below which is the array of data from the form which all looks correct.

However, there is no record in Saleforce. Org ID is correct, everything is
as it was when it was working 5 weeks ago.

I'm at a loss....

—
Reply to this email directly or view it on GitHub
<https://github.com/katzwebservices/Gravity-Forms-Salesforce/issues/193#issuecomment-88311819>
.

**Comment by adamfoale** [comment]
Hi Bill.

I understand that.  :-)  As I said, this has been working fine for over a year but suddenly stopped working a month or so ago.  

I've been doing this stuff for a long time so I know how to troubleshoot, but I hate it when things outside your control just suddenly stop working with seemingly no interest from the guys that built the plugin.  

![salesforce-api-broken](https://cloud.githubusercontent.com/assets/9222392/6933355/d54a366a-d871-11e4-8fdd-5c60db6ad807.png)

You can see from the screenshot that i have API selected as the integration method, but there is no 'Salesforce API' menu option on the left.

Thanks for the feedback anyway.

**Comment by zackkatz** [comment]
This will be fixed with the next update, coming soon. Thanks for reporting, and sorry for the issues.
