### ISSUE TITLE
Add to Contacts instead of Leads 

### ISSUE THREAD

**Issue by natalyabrandt** [katzwebservices/Gravity-Forms-Salesforce#194]
Is it possible to add Gravity Form entries directly to the SalesForce Contacts instead of the Leads with API implementation? If so, what kind of API will I need to use?

**Comment by Asuryan30** [comment]
Yes. If you use the API version of the plugin (Not the Web to lead) you can
do it.

2015-03-25 17:17 GMT-04:00 natalyabrandt <notifications@github.com>:
