### ISSUE TITLE
Settings when API method selected do not show

### ISSUE THREAD

**Issue by gallan** [katzwebservices/Gravity-Forms-Salesforce#197]
When the API integration method is selected, the settings tab (Salesforce API Settings) on the left does not show. Cleared cache and tried a few different times. Any ideas?

PHP version is 5.4, I saw that older versions of PHP could be contributing.

Thanks!

![screen shot 2015-04-02 at 5 47 03 pm](https://cloud.githubusercontent.com/assets/688218/6974672/bb08e836-d962-11e4-99b0-e17d3c0dbd1f.png)

**Comment by zackkatz** [comment]
This will be fixed with the next update, coming soon. Thanks for reporting.

**Comment by vivekbarange** [comment]
Hello, I am also having same issue. Please let me know the solution for the same.

I have followed below steps but got stuck in 3rd step, there is no link for Salesforce: API

### API
- Select API as your Integration Method
- Click Save Settings.
- Click the "Salesforce: API" menu in the current settings
- Click the "Login with Salesforce" button
- Log in to Salesforce.com
- Click on the Forms > Salesforce menu link to create a feed
- Follow the steps to create a feed

Thanks,
Vivek
