### ISSUE TITLE
Fatal Error on Install

### ISSUE THREAD

**Issue by geesam** [katzwebservices/Gravity-Forms-Salesforce#203]
Hi Team,

I'm getting this error on install: 

Fatal error: Call to undefined method GFForms::include_feed_addon_framework() in /home/sitename/public_html/wp-content/plugins/gravity-forms-salesforce/inc/kwsaddon.php on line 27

Running WP Version 4.1.1
Gravity Forms Version 1.7.5

Do I need a newer version of GF?

**Comment by zackkatz** [comment]
Yes, you do - I thought that I checked against earlier versions—sorry for the fatal error. You need at least 1.8.
