### ISSUE TITLE
Salesforce Gravity Forms Add-on not working

### ISSUE THREAD

**Issue by MartGordon** [katzwebservices/Gravity-Forms-Salesforce#210]
Hi, I have a site that I have taken over recently and migrated to WP Engine for hosting. For the first 4 days the Salesforce add-on for Gravity Forms has worked well. Since Friday the web lead to salesforce seems to be broken. 

The forms is here: http://www.metfilmschool.ac.uk/request-prospectus/ and I can not see the "Salesforce: Web-to-Lead" link on the form settings page. Can you tell me if this is a problem with the add-on's compatibility with the latest Gravity Forms update?

Thanks,

Mart

**Comment by plsitmanager** [comment]
Have you checked to see if API was enabled as this will switch off
web-to-lead?
