### ISSUE TITLE
SALESFORCE: API not appearing on settings menu

### ISSUE THREAD

**Issue by chirayubansal** [katzwebservices/Gravity-Forms-Salesforce#251]
Hi there,

I have installed the plugin, and when choosing the API version, there's no SALESFORCE: API menu item on the left hand side. The only one I can see it's the web-to-lead, when I choose that option on the settings.

PHP version: 5.4.43
Gravity Form version: 1.9.13
Gravity Forms Salesforce Add-on Version: 3.1.2

![image](https://cloud.githubusercontent.com/assets/15367538/10801239/62e35866-7ddc-11e5-9fd3-9157f4db8ee0.png)

Help is appreciated,
Regards

**Comment by hintontk** [comment]
I am having the same issue. The Salesforce menu to add feeds for the API used to reside under the Settings menu item, but is no longer available in my Wordpress dashboard. This occurred within the past 2 days.

GF: 1.9.14
GFSF: 3.1.2

![api](https://cloud.githubusercontent.com/assets/12075104/10829794/c2428664-7e41-11e5-9789-1542f0bd785d.jpg)

**Comment by chirayubansal** [comment]
Hi,
The problem has been resolved by reinstalling this plugin.

Regards
