### ISSUE TITLE
Version 3.1.2 Not working with WordPress 4.3.1

### ISSUE THREAD

**Issue by rweekes** [katzwebservices/Gravity-Forms-Salesforce#257]
Our wordpress network was upgraded to version 4.3.1. The upgrade disabled your 3.1.2 plugin. We backed up prior to the upgrade and have tried to rollback the upgrade unsuccessfully. Do you have an ETA of when you will support 4.3.1? This is mission critical to our site. Any help you can provide is appreciated!

Thanks,
Russ
rbw@weekeslaw.net

**Comment by rweekes** [comment]
NEVERMIND - the settings just needed to be reconfigured! I love the plugin! Thanks,

**Comment by ocoen68** [comment]
Hello Russ,
Could you explain  what is the the settings you find to make the plugin work on wp 4.3 ?

Thanks, 
Olivier

**Comment by rweekes** [comment]
Olivier - I didn't really have to make any significant changes. I use the
API settings and when we did the upgrade it removed the settings from the
admin console as if the plugin was first activated and wasn't configured. I
went into the Gravity Forms settings to the Salesforce Add-on section and
re-enabled the API Integration option and everything was back to normal.
All my prior settings were retained and active. Hope that helps.

Thanks,


Russell B. Weekes
Principal
*Weekes Law, PLLC*
rbw@weekeslaw.net <russ@utahbankruptcy.com>
P: (801) 657-5074
F: (888) 612-4236

UNAUTHORIZED INTERCEPTION OF THIS MESSAGE IS PROHIBITED BY FEDERAL LAW
PURSUANT TO 18 U.S.C. 2511 (2006).

*CONFIDENTIALITY NOTICE: This message and any files transmitted with it are
CONFIDENTIAL and intended for the use of the individual or entity to whom
it is addressed.  The information may also be protected by the
attorney-client privilege, work product immunity, or other legal
protections.  If you have received this email by mistake, please
immediately notify us by reply email or by calling us at (888) 818-9221 and
delete it from your system.  You may not copy or forward this message or
disclose its contents to anyone.  Email transmission cannot be guaranteed
to be secure or error-free as information could be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses.  The sender
therefore does not accept liability for any errors or omissions in the
contents of this message that arise as a result of email transmission.

 *CIRCULAR 230 DISCLOSURE:  Pursuant to U.S. Treasury Department
Regulations, any federal tax advice contained in this communication,
including attachments and enclosures, is not intended or written to be
used, and may not be used, for the purpose of (1) avoiding tax-related
penalties under the Internal Revenue Code; or (2) promoting, marketing, or
recommending to another party any tax-related matters addressed herein.

**Comment by ocoen68** [comment]
Thanks Russ

In fact my problem is that the API configuration is not accesssible and 
I have database connection failures.
So I understand that it could be solved by a instalation of a previous 
version of WP and then upgrade it after a first configuration...

Olivier

**Comment by rweekes** [comment]
That may work. I've had it installed on prior versions and was upgrading,
so I assume that would work.


Russell B. Weekes
Principal
*Weekes Law, PLLC*
rbw@weekeslaw.net <russ@utahbankruptcy.com>
P: (801) 657-5074
F: (888) 612-4236

UNAUTHORIZED INTERCEPTION OF THIS MESSAGE IS PROHIBITED BY FEDERAL LAW
PURSUANT TO 18 U.S.C. 2511 (2006).

*CONFIDENTIALITY NOTICE: This message and any files transmitted with it are
CONFIDENTIAL and intended for the use of the individual or entity to whom
it is addressed.  The information may also be protected by the
attorney-client privilege, work product immunity, or other legal
protections.  If you have received this email by mistake, please
immediately notify us by reply email or by calling us at (888) 818-9221 and
delete it from your system.  You may not copy or forward this message or
disclose its contents to anyone.  Email transmission cannot be guaranteed
to be secure or error-free as information could be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses.  The sender
therefore does not accept liability for any errors or omissions in the
contents of this message that arise as a result of email transmission.

 *CIRCULAR 230 DISCLOSURE:  Pursuant to U.S. Treasury Department
Regulations, any federal tax advice contained in this communication,
including attachments and enclosures, is not intended or written to be
used, and may not be used, for the purpose of (1) avoiding tax-related
penalties under the Internal Revenue Code; or (2) promoting, marketing, or
recommending to another party any tax-related matters addressed herein.
