### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on localhost

### ISSUE THREAD

**Issue by jochembeumer** [katzwebservices/Gravity-Forms-Salesforce#311]
I'm trying to use this plugin on a local configuration and I'm getting a ERR_TOO_MANY_REDIRECTS error on Safari, Firefox and Chrome. I'm using MAMP Pro with a self signed certificate.

**Comment by millardsimon** [comment]
Today my site updated to Wordpress 4.5.2 and I now get ERR_TOO_MANY_REDIRECTS error on Safari, Firefox and Chrome when trying to authenticate my salesforce connection.  It was ok sending to Salesforce but I needed to change the authenticated user, I therefore revoked the access and can't re-connect.  
Error on page:
The katz.co page isn’t working
katz.co redirected you too many times.

Error from logging tool:
2016-05-31 13:58:04.519438 - DEBUG --> get_api(): The access token is empty - app is not yet authenticated

**Comment by jeffhonnold** [comment]
Same issue here.

Best guess: katz.co is failing.  If you simply try to visit http://katz.co it doesn't work.

katz.co is part of the oauth sign-in process to salesforce; hence, if katz.co doesn't work, the sign-in process doesn't work.

Best guess of a solution: resolve issue at katz.co itself.

**Comment by danhq** [comment]
Hello I am getting the same error when trying to connect.

**Comment by RichSykes2016** [comment]
I have the same error, 
https://katz.co/ doesn't respond and is causing me a problem with a live system.

**Comment by FM2016** [comment]
Hello, I am setting up a new system and have been getting the same error trying to connect.
![image](https://cloud.githubusercontent.com/assets/19689081/15712646/12740900-280b-11e6-9d72-c083c5626e90.png)

**Comment by inderpreet99** [comment]
The error seems to have been fixed. This issue can probably be closed if someone else can verify this.

**Comment by FM2016** [comment]
I agree, thanks very much!
