### ISSUE TITLE
TLS 1.0 not supported

### ISSUE THREAD

**Issue by CaptainValor** [katzwebservices/Gravity-Forms-Salesforce#328]
When attempting to log in to Salesforce via the button in the "Salesforce: API" page of Gravity Forms, I am received the error that "TLS 1.0 is no longer supported" and that only TLS 1.1 and higher should be used.

Due to this, I am unable to use the plugin. Is there a workaround?

**Comment by coadr** [comment]
How to solve this? I will probably be running in to this issue myself..

**Comment by CaptainValor** [comment]
In Salesforce, navigate to...
**Setup > Build - Critical Updates > Deactivate: Require TLS 1.1 or higher for HTTPS connections**
